apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  annotations:
    avp.kubernetes.io/path: "demo/data/argocd-vault-plugin-demo/demo-secret"
type: Opaque
stringData:
  TOKEN: <password>
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret-inline
type: Opaque
stringData:
  TOKEN: <path:demo/data/argocd-vault-plugin-demo/demo-secret#password>
