apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin-demo-charts
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: demo-secrets-charts
    server: https://kubernetes.default.svc
  project: default
  source:
    path: secrets-test
    repoURL: https://github.com/herveleclerc/argocd-vault-plugin-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
