apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin-demo
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: demo-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    #plugin:
    #  env:
    #    - name: AVP_TYPE
    #      value: vault
    #    - name: AVP_AUTH_TYPE
    #      value: token
    path: secrets
    repoURL: https://github.com/herveleclerc/argocd-vault-plugin-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
